### ISSUE TITLE
Not showing up in extensions

### ISSUE THREAD

**Issue by godofgrunts** [HorrorPills/ChatGPT-Gnome-Desktop-Extension#14]
Running `sudo make install` as suggested doesn't install the extension in the local user's extension directory. Instead it installs it to `/root/.local/share/gnome-shell/extensions/`

Manually running 

```
mkdir -p ~/.local/share/gnome-shell/extensions/
cp -r ./chatgpt-gnome-desktop@chatgpt-gnome-desktop ~/.local/share/gnome-shell/extensions/
```
And then restarting X allows the extension to show up in gnome-extensions.

**Comment by godofgrunts** [comment]
Also as a side note, it seems to be working in Wayland as well (though the servers are down so I can't do anything with it at the moment).

**Comment by o69mar** [comment]
just run `make install` without sudo
