### ISSUE TITLE
No such new app seen after installing

### ISSUE THREAD

**Issue by Axoncodes** [HorrorPills/ChatGPT-Gnome-Desktop-Extension#18]
I did go through the process of installing on ubuntu and did the Extra command as well
Am I supposed to see a new app in the menu to run or a file to run as an app or sth? because I see no such thing!

**Comment by faheemKamboh** [comment]
@Axoncodes ,
I faced the same issue, that was it's not enabled by default.
can you confirm that you enabled the extension with the following command?

`gnome-extensions enable chatgpt-gnome-desktop@chatgpt-gnome-desktop`

**Comment by Axoncodes** [comment]
At which stage or location should I run it? This is response of the command you mentioned:
```
-gnome-desktop
Extension “chatgpt-gnome-desktop@chatgpt-gnome-desktop” does not exist
```

**Comment by Axoncodes** [comment]
> @Axoncodes , I faced the same issue, that was it's not enabled by default. can you confirm that you enabled the extension with the following command?
> 
> `gnome-extensions enable chatgpt-gnome-desktop@chatgpt-gnome-desktop`

At which stage or location should I be running the command? the response of the command u mentioned is:
`Extension “chatgpt-gnome-desktop@chatgpt-gnome-desktop” does not exist`

**Comment by Axoncodes** [comment]
@faheemKamboh Oh the main problem was restarting, and then running the command u mentioned, did the job, thanks a lot

**Comment by faheemKamboh** [comment]
> > @Axoncodes , I faced the same issue, that was it's not enabled by default. can you confirm that you enabled the extension with the following command?
> > `gnome-extensions enable chatgpt-gnome-desktop@chatgpt-gnome-desktop`
> 
> At which stage or location should I be running the command? the response of the command u mentioned is: `Extension “chatgpt-gnome-desktop@chatgpt-gnome-desktop” does not exist`

So what I did was, after following the given flow, I checked all disabled extensions in by `ubuntu 22.04.1` with following command
`gnome-extensions list --disabled`
Output of the command was something like
`chatgpt-gnome-desktop@chatgpt-gnome-desktop`
then I entered following command
`gnome-extensions enable `_{hit twice/thrice tab, which should autocomplete disabled extension(if only one) or you can paste the extension name}_

**Comment by suleman-uzair** [comment]
> @faheemKamboh Oh the main problem was restarting, and then running the command u mentioned, did the job, thanks a lot

Great!
If it's resolved, should close the issue.

**Comment by faheemKamboh** [comment]
> @faheemKamboh Oh the main problem was restarting, and then running the command u mentioned, did the job, thanks a lot

Great! Happy to Help,

If it's fixed, you should close the issue!

**Comment by Axoncodes** [comment]
> Enabling the extension inside gnome-shell-extensions is necessary :)

noted, thanks
