### ISSUE TITLE
LMDE 5, trouble finding it

### ISSUE THREAD

**Issue by Nam-Ram** [HorrorPills/ChatGPT-Gnome-Desktop-Extension#2]
This is really cool! Probably user error (linux newbie but learning), but there were enough inconsistencies with the instructions and my distro (LMDE - Debian based Mint) in case anyone else is struggling. Doesn't seem to be listed under installed applications, or available as an applet, or a Desklet.

`Place the chatgpt-gnome-desktop@chat-gpt-gnome-desktop folder in ~/.local/share/gnome-shell/extensions/`

I do not have that destination folder, I put it in `/usr/share/gnome-shell/extensions` instead

I did restart Gnome a few times

I'm running x11, but Gnome Shell 3.38.6

When trying to run `sudo apt install libgtk-4-dev` I get `Unable to locate package` - seems like updating to 42 would be a major change that I'm not in a place to do, but not sure if that would stop it from showing up somewhere.

Thanks!

**Comment by HorrorPills** [comment]
Do not touch usr/share/...

Make sure you have gnome-extensions installed. 
You can enable the extension in the gnome-extensions app.

Once installed, put the chatgpt-gnome-desktop@chat-gpt-gnome-desktop folder in ~/.local/share/gnome-shell/extensions/

Then restart Gnome Desktop Enviorment or Log out and log back in

**Comment by nordcomputer** [comment]
Are you even using the Gnome DE?

**Comment by Nam-Ram** [comment]
> @Nam-Ram Are you even using the Gnome DE?

Hmm, I'm not sure.

`$ echo $XDG_CURRENT_DESKTOP` returns `X-Cinnamon`, which seems to be a fork of Gnome3.

**Comment by nordcomputer** [comment]
X-Cinnamon != Gnome.

**Comment by HorrorPills** [comment]
I have not tested how the extension works on forks of Gnome. In the extensions early development stage, Gnome 42 is used with focus on bringing compatibility to Gnome 43.
