### ISSUE TITLE
Forgets login

### ISSUE THREAD

**Issue by fuzebox1** [HorrorPills/ChatGPT-Gnome-Desktop-Extension#30]
With the mouse fix implemented i can use the extension finally. However, after logging in, each time i close the window by clicking either the icon or outside the window, the login is forgotten and i have to login again.
Is this intended or is there some cookie issue perhaps?

**Comment by Im-Stivik** [comment]
it is still in progress, the last commit wasnt suppose to be published yet since it removed this to enable another thing, for now i suggest you to roll back two commits and use it without the mouse and in xorg

**Comment by fuzebox1** [comment]
Use it without the mouse in xorg? It cant be used without the mouse, how am i supposed to select things without the mouse when the window elements cant be selected? This is the first time i've been able to use the ext at all.
Also, what makes it not work on wayland? 
Not to sound ungrateful, im not.

**Comment by Im-Stivik** [comment]
This project is still in development and still unusable for the most part

For your question, we tried to make the window open in the same process as the gnome extantion and for some reason it doesn't let the mouse interact with the window and also the keyboard in Wayland

You can navigate using the tab button on the keyboard if you are using xorg.

I hope we will manage to fix this in a few days
